### ISSUE TITLE
B2B/Enterprise Use Case Documentation from old xdaichain site

### ISSUE THREAD

**Issue by ice09** [gnosischain/documentation#118]
Some time ago I wrote something about B2B/Enterprise use cases on GC, but this site is now said to have moved: https://developers.gnosischain.com/about-gc/use-cases/b2b-and-enterprise-applications
But I can't find it anywhere on the new page.

Just want to make sure it did not get lost while migrating - if it is still of interest, I could update it for the most current state of chains etc. If you don't need it anymore it's fine as well - though I still think B2B/Enterprise use cases could fit very well to GC.

**Comment by alebanzas** [comment]
Reference: https://github.com/gnosischain/docs/blob/1809abc81a73fc400c6a0c2db9da4e2f368d874a/about-gc/use-cases/b2b-and-enterprise-applications.md

**Comment by ice09** [comment]
Thanks! Will it be included, so should I update it?

**Comment by alebanzas** [comment]
@ice09 I think we could include it under the "ecosystems" section. wdyt? If you agree, please, feel free to make the updates and PR 🥇

**Comment by alebanzas** [comment]
@ice09 it could be a dedicated section.

**Comment by ice09** [comment]
Ok, what would be the name then, "B2B (Use Cases)"? "Enterprise"?

**Comment by alebanzas** [comment]
I would go with "Enterprise", and try to point to some internal pages. I.e: "Statistics & Chain Properties" could be linked directly to [Specs](https://docs.gnosischain.com/specs/) instead of repeating the info. This makes it easy to maintain the info when it is only in one place, and also it helps build SEO by cross-linking the content.

**Comment by ice09** [comment]
Nice, thanks. When will it be online?

**Comment by alebanzas** [comment]
Will go online this week with other changes :)
