### ISSUE TITLE
content: DApps should create a page for themselves in Ecosystem with contract addresses

### ISSUE THREAD

**Issue by dan-gnosis** [gnosischain/documentation#123]
## What

- DApps should create a page for themselves in the Ecosystem section of docs
- Should identify the key smart contract addresses they have
- Should also label and verify their smart contracts in Sourcify / Etherscan

We discussed during retreat that this should be a precursor for any grant funding / marketing engagement.

**Comment by alebanzas** [comment]
We can document the process with a sample page + template + issue.

**Comment by alebanzas** [comment]
Dapp Developers, please create your proposal before adding your dapp here: https://github.com/gnosischain/documentation/issues/new?assignees=&labels=documentation%2Cdapp&template=suggest_dapp.yaml&title=Suggest+a+dapp
