### ISSUE TITLE
Adjusting wording for hardhat for javascript for newer developers

### ISSUE THREAD

**Issue by billyjitsu** [gnosischain/documentation#137]
**Adjusting "Using Hardhat Section" To Javascript**

In the current section 
https://docs.gnosischain.com/developers/smart-contracts/hardhat

The instructions gives examples in typescript with a mnemonic key phrase.  
Many new developers come in with Javascript examples and with a .env "PRIVATE_KEY" type setup in the hardhat.config.js file.

This could lead to slight confusion with wanting to experiment with Gnosis from other EVM chains easily.

Possibly giving a javascript example as well would help ease the transition/experimentation to Gnosis chain for new developers.

**Comment by alebanzas** [comment]
Solved here: https://github.com/gnosischain/documentation/pull/382 
To be included in the next release
