### ISSUE TITLE
Validators - Technical Requirements

### ISSUE THREAD

**Issue by alebanzas** [gnosischain/documentation#143]
Current info: https://docs.gnosischain.com/node/consensus-layer-validator#the-basics

- [ ] Check validity of current docs info
- [ ] Technical requirements to run the Gnosis validator set (EL+CL)
- [ ] Calculate and show scenarios of solo validator costs (energy, internet, hardware, etc)

**Comment by plato-gno** [comment]
Task deprecated, included in Overview section (and in individual client requirements)
