### ISSUE TITLE
Chiado page needs updating

### ISSUE THREAD

**Issue by broadbentg** [gnosischain/documentation#162]
## What

The Chiado page has not been updated even though the Chiado testnet has apparently been reset.  There should be a warning if the testnet is not actually up.  If it is up, this information must refer to the old testnet.

## Why

When people go to this page to set up the testnet, it is confusing that it is not actually up or the information is wrong.

## Refs

https://docs.gnosischain.com/about/networks/chiado
https://discord.com/channels/502416149343109121/1006331943975125084/1023888260415639592

New testnet:

https://discord.com/channels/502416149343109121/1006331943975125084/1025172441548455946
https://twitter.com/gnosischain/status/1575584323180187650

**Comment by alebanzas** [comment]
Thanks @broadbentg ! I will link the [PR](https://github.com/gnosischain/documentation/pull/158) we are working on with this issue.

**Comment by alebanzas** [comment]
Will merge the PR without [Bridges with Goerli](https://docs.gnosischain.com/about/networks/chiado#contracts). AMB bridge will be deployed next week.
