### ISSUE TITLE
bug: Chiado has not transitioned to proof-of-stake

### ISSUE THREAD

**Issue by peter-gnosis** [gnosischain/documentation#174]
## What

See https://docs.gnosischain.com/about/networks/chiado

"...it is the first network transitioned to Proof of Stake..."

I believe the current plan is to test the merge on Chiado before the mainnet, so this statement is probably not
correct.  (I'm willing to be be corrected myself if I've got this wrong!)

**Comment by alebanzas** [comment]
solved already. thanks @plato-gno !

**Comment by plato-gno** [comment]
Thank you @peter-gnosis for being a QA!!!

**Comment by peter-gnosis** [comment]
You're welcome!
