### ISSUE TITLE
bug: Chiado Reset Warning Should Be On Chiado Page, plus two other suggestions

### ISSUE THREAD

**Issue by peter-gnosis** [gnosischain/documentation#175]
## What

See https://docs.gnosischain.com/about/networks/

At the bottom of the page, there is a "Chiado Reset" warning.  Shouldn't that be on the Chiado page?:
https://docs.gnosischain.com/about/networks/chiado

If somebody goes directly to the page (I've done this), they won't see the warning.

Also, would it be helpful if the reset warning gave the old Chain ID and the new Chain ID?

And, right now it says to point your node to the new RPC endpoint.  Would it be a good
idea to give the old RPC endpoint?  For example, "change your RPC endpoint from rpc.foo.bar
to rpc.chiadotestnet."

**Comment by alebanzas** [comment]
Added here: https://docs.gnosischain.com/about/networks/chiado#previous-iterations
