### ISSUE TITLE
Improvement: Show Author, Last Verified, and Request Update in Docusaurus

### ISSUE THREAD

**Issue by plato-gno** [gnosischain/documentation#195]
Inspired by Prysm's Docusaurus

https://docs.prylabs.network/docs/install/install-with-script

![Image](https://user-images.githubusercontent.com/98335261/199025410-5aaba871-dbb1-4fa0-8efe-b7a37c9ac805.png)

**Comment by alebanzas** [comment]
https://github.com/prysmaticlabs/documentation/blob/master/website/src/components/HeaderBadgesWidget.js

**Comment by alebanzas** [comment]
Adding update date + author.  

<img width="878" alt="image" src="https://user-images.githubusercontent.com/1384638/205183317-27f9c6fc-344b-46c0-8b45-1610109847ba.png">

A better implementation is coming to Docusaurus: https://github.com/facebook/docusaurus/issues/6218
