### ISSUE TITLE
Use Sedge-generated Dockerfiles for Consensus Layer section

### ISSUE THREAD

**Issue by plato-gno** [gnosischain/documentation#234]
## Objective 

- [x] Replace @CVJoint's dockerfiles with Sedge-generated Dockerfiles
- [x] For Docker, recommend users to use Sedge to generate it (use a [admonition](https://docusaurus.io/docs/markdown-features/admonitions)
- [x] Edit the Sedge-generated Dockerfiles to use our current file structure
- [x] Align with Sedge's Docker best practices (e.g. don't hard-code IP addresses, etc)

Example of a Sedge Dockerfile:

https://docs.sedge.nethermind.io/docs/quickstart/complete-guide#3-generate-a-docker-compose-script-with-a-randomized-set-of-execution-consensus-and-validator-clients

## Long-term problem 

- [ ] How do we marry our "file structure" that we are recommending, vs Sedge's auto-generated file structure? 
- [ ] Should we align with Sedge's auto-generated file structure?

**Comment by CVJoint** [comment]
The new docker-compose files should align with the Sedge output at this time, with the main differences being:
- Containers are named `execution-client`, `consensus-client`, and `validator client.
- Different folder structures (on host and in container).
  - Sedge uses a host folder structure like: 
  - 
```
/home/$USER/docker-compose-scripts/
├── jwtsecret (file)
├── execution-data/
└── consensus-data/
```

Regarding the use of Sedge and future alignment - I think there is value to keep a complete example in the docs. There are not expected to be many changes to the files in the future, however Sedge method would requires manual client version updates. I propose to keep Sedge separate and to update any major changes to the docs manually.
