### ISSUE TITLE
Implement Redirects within Docusaurus for outdated pages

### ISSUE THREAD

**Issue by plato-gno** [gnosischain/documentation#235]
https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-client-redirects

- e.g. [docs.gnosischain.com/bridges/ove](https://docs.gnosischain.com/bridges/overview) should be an automatic redirect to https://docs.gnosischain.com/bridges/
- We should continually update the redirects, everytime we move a page in documentation

**Comment by alebanzas** [comment]
Redirects from old "run a node" structure to the new one planned here: https://docs.google.com/spreadsheets/d/1ki1NJ3LscDpZHc1VI-zrM5p5tgNPo4MN4p-4wn7jYxg/edit#gid=1700733935

[plugin-client-redirects](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-client-redirects) unfortunately are client redirects, we will implement server HTTP permanent redirects.

**Comment by alebanzas** [comment]
Redirects implemented on the server.

> From an SEO point of view, a server-side redirect should always be preferred over a client-side redirect. The major downside to client-side redirects is the missing information about the reason for the redirect, making it harder for search engines to make a decision on how the redirect should be treated.
