### ISSUE TITLE
Implement Redirects in Gitbook for legacy developers.gnosischain.com pages

### ISSUE THREAD

**Issue by plato-gno** [gnosischain/documentation#236]
We may be able to specify the `basepath` as the new docs.gnosischain.com site, and redirect developers.gnosischain.com to the new site

https://github.com/getgauge-contrib/gitbook-plugin-bulk-redirect/blob/master/README.md#redirects-in-redirectsjson

**Comment by alebanzas** [comment]
Old website still hosts `Optimism on GC` information. We need to transfer those first, then generate HTTP permanent redirects and deprecate gitbook.

**Comment by alebanzas** [comment]
Dependency: https://github.com/gnosischain/documentation/issues/190

**Comment by plato-gno** [comment]
I was actually thinking of doing the migration 1-by-1, and defining custom 302 rules for each page that we migrate. 

I was trying to find an old page from the Gitbook yesterday (regarding ETHDenver 2019). Unfortunately the page got redirected, even though the content was not migrated. 

We can probably use the lull after the Merge to re-pick up on the docs effort, hopefully with more contributors this time from the community. There's a lot of resources in the old docs (news articles, etc), and it'd be a great way for new contributors to learn more about the chain's history.

**Comment by alebanzas** [comment]
[URL Planning](https://docs.google.com/spreadsheets/d/1ki1NJ3LscDpZHc1VI-zrM5p5tgNPo4MN4p-4wn7jYxg/edit#gid=375656827) tab `redirects developers`

**Comment by alebanzas** [comment]
Dependencies:
- [ ] https://github.com/gnosischain/documentation/issues/72
- [ ] https://github.com/gnosischain/documentation/issues/327
