### ISSUE TITLE
Validator File Structure should be a partial and consistent across pages

### ISSUE THREAD

**Issue by plato-gno** [gnosischain/documentation#238]
## Objective

- We currently have a lot of repeated Markdown across files describing the same thing
- This should be a partial and imported across the different files

## Folder Structure and creating folders

Interactive Guide
- [ ] http://localhost:3000/node/guide/#step-1-configure-server

Run Beacon Node
- [ ] http://localhost:3000/node/guide/beacon/lodestar#1-folder-structure
- [ ] http://localhost:3000/node/guide/beacon/lighthouse#1-folder-structure
- [ ] http://localhost:3000/node/guide/beacon/teku#1-folder-structure

## Keystore Location

Run Beacon Node
- [ ] http://localhost:3000/node/guide/beacon/lighthouse#4-keystore-location
- [ ] etc

**Comment by alebanzas** [comment]
Done with Beacon.
N/A for validators, clients differ on how they expect the key/password paths
