### ISSUE TITLE
Interactive Guide needs a CL client summary for Lodestar, Nimbus, Prysm, Teku

### ISSUE THREAD

**Issue by plato-gno** [gnosischain/documentation#243]
## Objective

Currently, the Interactive Guide does not have a CL client summary for Lodestar, Teku, (and Prysm, Nimbus)
- Step 3: Run a Beacon Node
- Step 4b: Run a Validator

We would ideally have the "Option 1: Run as System Process" for each CL client available as partial to be imported. 

## Interim solution

- [ ] If "Option 1: Run as System Process" is available for Lodestar, Teku, link to it
- [ ] Otherwise, link to the actual page itself (e.g. http://localhost:3000/node/guide/beacon/lodestar)

## Resources

![Image](https://user-images.githubusercontent.com/98335261/203395197-19159d01-c946-4657-90e0-10307b9cf748.png)

**Comment by alebanzas** [comment]
Not needed now, tabs are disabled.
