### ISSUE TITLE
Social previews for Docs site should show the title and description of the page

### ISSUE THREAD

**Issue by plato-gno** [gnosischain/documentation#261]
## Problem

Currently, pages in docs.gnosischain.com don't have a "social media preview" - instead just showing the main page. 

![Image](https://user-images.githubusercontent.com/98335261/203791734-1c6befa9-84e2-4bda-9afd-95f803aaf160.png)

## Outcome

Pasting a page from docs.gnosischain.com should show
- Image (if possible)
- Correct title
- Correct description (or snippet of first few lines)

https://developers.facebook.com/tools/debug/
- Paste a docs.gnosischain.com URL here too

**Comment by alebanzas** [comment]
Duplicated: https://github.com/gnosischain/documentation/issues/252

**Comment by alebanzas** [comment]
For future research: https://blog.bitsrc.io/the-sharing-part-2-generating-images-using-html-canvas-in-javascript-6fee4e320c4

Dynamic generation of image with its title.
