### ISSUE TITLE
Localhost server keeps hot reloading even though no changes were made

### ISSUE THREAD

**Issue by plato-gno** [gnosischain/documentation#269]
Not sure if any of you are experiencing it, but my localhost keeps hot reloading even though no changes are made

![Image](https://user-images.githubusercontent.com/98335261/204213167-7ae29919-7f9c-4ef1-be32-b8fc95f8c25e.png)

**Comment by alebanzas** [comment]
Issue reported to the plugin. https://github.com/rdilweb/docusaurus-plugin-remote-content/issues/51

Will not happen again after I remove the plugin, see related issue: https://github.com/gnosischain/documentation/issues/270
