### ISSUE TITLE
Consider linking to Validator Deposit Data's Github README instead of embedding doc

### ISSUE THREAD

**Issue by plato-gno** [gnosischain/documentation#270]
## Suggestion

- With the refactor from #264 , there are now 2 docs for generating Validator Deposit data
- Can we consider just sticking to the documentation, and then referring the user over to the Github README if they want more in-depth docs?

![Image](https://user-images.githubusercontent.com/98335261/204214945-1b810e00-7aec-4640-849a-6610a538f163.png)

**Comment by alebanzas** [comment]
Will remove it. Remote content can be added in the future when more pages need it.
