### ISSUE TITLE
bug: `Run Validator` > `Keystore Location` has the wrong dir structure

### ISSUE THREAD

**Issue by 0xSage** [gnosischain/documentation#280]
1. Instructions here https://docs.gnosischain.com/node/guide/validator/generate-keys/cli/, i.e. the CLI tool creates validator keystores under `keystores/validator_keys`
2. Subsequent instructions here: https://docs.gnosischain.com/node/guide/validator/run/lighthouse#4-keystore-location reflect a different file structure, leading to users possibly copying/moving their keystores up 1 directory, which is hairy. 
3. Suggestion, just delete section 4, and have users configure: 
```
docker run \
  --rm \
  --volume /home/$USER/gnosis/consensus/keystores:/keystores \
  --volume /home/$USER/gnosis/consensus:/data sigp/lighthouse:latest-modern lighthouse account validator import \
  --network gnosis \
  --password-file /keystores/password.txt \
  --reuse-password \
  --directory /keystores/validator_keys \ ## double check this
  --datadir /data
```

Honestly , this is a nit, not critical. The documentation is already really good. This section just gave me a bit of pause.

**Comment by alebanzas** [comment]
Related issue: https://github.com/gnosischain/documentation/issues/238

**Comment by alebanzas** [comment]
Will be deployed today.
