### ISSUE TITLE
Hyperlinks should be more easily identified

### ISSUE THREAD

**Issue by dan-gnosis** [gnosischain/documentation#29]
Problem: 
![image](https://user-images.githubusercontent.com/98335261/181408274-b587f581-12c2-4e51-ae6c-53d43a62f150.png)

Solution: 
![image](https://user-images.githubusercontent.com/98335261/181408329-406b5e74-222c-4a20-8913-1583616da403.png)

**Comment by alebanzas** [comment]
This is happening in the "light" theme.
