### ISSUE TITLE
Bridge section should have Overview that tells user to use 3rd-Party Bridges, and explains role Native Bridges play

### ISSUE THREAD

**Issue by plato-gno** [gnosischain/documentation#295]
- docs.gnosischain.com/bridges should be an informative article for end-users, direct them to Li.Fi or 3rd-party bridges
- Explain the role of Native Bridges (AMB, mint/burn for canonical tokens)
- Explain roadmap - e.g. Native Bridges become more of APIs, are integrated by 3rd-party bridges

**Comment by vanshika-srivastava** [comment]
Already completed and merged! 
https://www.linkedin.com/in/houlgrave
