### ISSUE TITLE
Run a Node should have an expanded section on Metrics, including ethstats, forkmon, Prometheus/Grafana

### ISSUE THREAD

**Issue by plato-gno** [gnosischain/documentation#296]

**Comment by zengzengzenghuy** [comment]
**Ref:**
[Guide on how to do monitoring for an Ethereum validator](https://github.com/eth-educators/ethstaker-guides/blob/main/monitoring.md):Explain about installing node exporter, Prometheus, Grafana and adding monitoring to Ethereum clients.

**Comment by zengzengzenghuy** [comment]
Taking this issue
