### ISSUE TITLE
Fix images width on documentation pages

### ISSUE THREAD

**Issue by dan-gnosis** [gnosischain/documentation#33]
- Text Width on doc pages seems strange (but this is the Docusaurus default?)
- Recommend following [Readability Guidelines for Text Width](https://baymard.com/blog/line-length-readability) which is 50 to 75 characters

![image](https://user-images.githubusercontent.com/98335261/182046877-a64c0c45-7a3a-43a3-87ab-32f8d59593cb.png)

**Comment by alebanzas** [comment]
![Screenshot 2022-08-02 at 12 33 31](https://user-images.githubusercontent.com/1384638/182354744-84a08a80-0373-411c-b299-dcb1ba53307b.png)

@dan-gnosis check the layout width (red) vs the image size (yellow). it seems that the image is not using the whole width of the page, which makes us think that "text width" is the problem when the width of the images is.
