### ISSUE TITLE
bug: Updates URLs were broken by shift to folder structure

### ISSUE THREAD

**Issue by plato-gno** [gnosischain/documentation#335]
https://docs.gnosischain.com/updates/20221208-temporary-bootnodes is inaccessible (credit to @peter-gnosis for discovery)

Fix: 
- [ ] Temporary Client side redirects
- [ ] Server-side redirects
- [ ] Confirm long-term structure for URLs and stick to it!!!

Structural fix
- [ ] Research: is there a way to have backward URL compatibility (i.e. prevent merge if URLs would be broken?)

**Comment by peter-gnosis** [comment]
(Strictly speaking @segun found it! ;-) )
