### ISSUE TITLE
content: List of Checkpoint Sync servers

### ISSUE THREAD

**Issue by plato-gno** [gnosischain/documentation#343]
- [x] https://checkpoint.gnosischain.com
- [x] https://checkpoint.gnosis.gateway.fm
- [x] https://checkpoint-sync-gnosis.dappnode.io/

**Comment by zengzengzenghuy** [comment]
Cannot open https://checkpoint-sync-gnosis.dappnode.io/ : 404 page not found

**Comment by zengzengzenghuy** [comment]
Checkpoint sync is listed in https://docs.gnosischain.com/about/networks/mainnet#consensus-layer

![Screenshot from 2023-04-04 12-31-42](https://user-images.githubusercontent.com/85567868/229687641-ea532eef-7e31-44da-82bc-4c08db2f97ae.png)

**Comment by zengzengzenghuy** [comment]
Chiado Checkpoint sync server: 

- [x] https://checkpoint.chiadochain.net/

https://docs.gnosischain.com/about/networks/chiado#key-infra
