### ISSUE TITLE
Goerli <> Chiado Bridges

### ISSUE THREAD

**Issue by alebanzas** [gnosischain/documentation#378]
Document Goerli <> Chiado bridges
- [x] XDAI bridge
- [x] Omnibridge

# Addresses
 
## Chiado <> Goerli

- GNO on Goerli: `0x7f477c3f03213970d939104cc436dc995cf615b5`
- GNO on Chiado: `0xf907903Be10FC3a885d331C4E225794436a34c9f`
- Home OmniBridge Mediator: `0x09D549a48AC52F3f9945E7de6402c609c92aa2E1`
- Home AMB: `0x99Ca51a3534785ED619f46A79C7Ad65Fa8d85e7a`
- Foreign OmniBridge Mediator: `0x00147c84f13764dCDAbAF1cbAe622fa6f6839085`
- Foreign AMB: `0x87A19d769D875964E9Cd41dDBfc397B2543764E6`
- Validator address: `0xc9ADb79B8A6e7C6e90c765A3B4d16d81213c9D49`

# Scenario 1: Bridge from Goerli to Chiado

### Goerli - Transaction 1 - Allow Foreign OmniBridge Mediator to transfer GNOs
```
GNO.approve(address Foreign OmniBridge Mediator, uint256  amount)
to: 0x7f477c3F03213970d939104CC436Dc995CF615b5 (GNO on Goerli)
value: 0
data: 0x095ea7b300000000000000000000000000147c84f13764dcdabaf1cbae622fa6f683908500000000000000000000000000000000000000000000d3c21bcecceda1000000
```

### Goerli - Transaction 2 - Relay tokens
```
Foreign_OmniBridge_Mediator.relayTokens(address _receiver, uint256 _value)
to: 0x00147c84f13764dcdabaf1cbae622fa6f6839085 (Foreign OmniBridge Mediator)
value: 0
data: 0x01e4f53a0000000000000000000000007f477c3f03213970d939104cc436dc995cf615b50000000000000000000000000000000000000000000000000de0b6b3a7640000
```

After a few minutes the exact amount of relayed tokens will be available on Chiado side.

# Scenario 2: Bridge from Chiado to Goerli

### Chiado - Transaction 1: Allow Home OmniBridge Mediator to transfer GNOs
```
GNO.approve(address Home OmniBridge Mediator, uint256 amount)
to: 0xf907903Be10FC3a885d331C4E225794436a34c9f
value: 0
data: 0x095ea7b300000000000000000000000009d549a48ac52f3f9945e7de6402c609c92aa2e100000000000000000000000000000000000000000000d3c21bcecceda1000000
```

### Chiado - Transaction 2: Relay tokens
```
Home_OmniBridge_Mediator.relayTokens(address _receiver, uint256 _value)
to: 0x09D549a48AC52F3f9945E7de6402c609c92aa2E1
value: 0
data: 0x01e4f53a000000000000000000000000f907903be10fc3a885d331c4e225794436a34c9f0000000000000000000000000000000000000000000000000de0b6b3a7640000
```

**This last step must be tested thoroughly**

**Comment by zengzengzenghuy** [comment]
All transactions are tested:
**Goerli:**
Tx 1: Approve: https://goerli.etherscan.io/tx/0xc9382aaf2cde14b76a2906649b42ba0a8902ddff1af1efa8f1f30098a9a9e7db
Tx 2: Relay Token: https://goerli.etherscan.io/tx/0x9f194b138e67b297575822a4484083eae90e40859b3966531faff956d1e5692b
**Chiado:**
Tx 1: Approve: https://blockscout.com/gnosis/chiado/tx/0xf5378a47916f11437498d0593a1fe3d0abb1dc0aa4b6f884545d9fd0f0b0e858
Tx 2: Relay Token: https://blockscout.chiadochain.net/tx/0x23c92403de3f68a4d016e000e01200e02059876be9ef0898121cc37a6b5e2691

**Comment by zengzengzenghuy** [comment]
Close with [7fb3ee8](https://github.com/gnosischain/documentation/commit/7fb3ee83daeb6a174d18404b926b6018b7100ebb)
