### ISSUE TITLE
content: Add BlockSpaces to RPC Providers

### ISSUE THREAD

**Issue by christylerblockspaces** [gnosischain/documentation#380]
On the RPC Provider README.mdx
## BlockSpaces Free Gnosis RPC Endpoints

- [BlockSpaces Free RPC Endpoints](https://www.blockspaces.com/web3-infrastructure) 

<Tabs>
<TabItem label="Mainnet" value="Mainnet">

```
https://web3endpoints.com/gnosischain-mainnet
```

</TabItem>
<TabItem label="Archival" value="Archival">

```
https://web3endpoints.com/gnosischain-archival
```

</TabItem>
</Tabs>

For the sidebar.js, could we add this?

,
{
  type: 'link',
  label: 'BlockSpaces',
  href: 'https://www.blockspaces.com/web3-infrastructure',
},

**Comment by alebanzas** [comment]
will be online in the next release, thanks!
