### ISSUE TITLE
content: fee mechanism for rewards & penalties

### ISSUE THREAD

**Issue by zengzengzenghuy** [gnosischain/documentation#396]
# What
In [Rewards & Penalties](https://docs.gnosischain.com/node/rewards-penalties), we need to add more details on:
1. How rewards are calculated in CL and EL for proposing and attesting blocks.
2. How fee is burnt in EL.

# Ref
* https://forum.gnosis.io/t/launch-parameters-for-gnosis-beacon-chain-gbc/2200
* https://ethereum.org/en/developers/docs/consensus-mechanisms/pos/rewards-and-penalties/
* https://eth2book.info/bellatrix/part2/incentives/

**Comment by AnmolSirola** [comment]
@zengzengzenghuy Can I work on this issue ?

**Comment by zengzengzenghuy** [comment]
Yes @AnmolSirola

**Comment by AnmolSirola** [comment]
@zengzengzenghuy I have written the content for both How rewards are calculated in CL and EL for proposing and attesting blocks and how fee is burnt in EL.

But I am not confused where to specificaly add them, should I create a new section for How fee is burnt in EL.

**Comment by zengzengzenghuy** [comment]
I would suggest putting them under https://docs.gnosischain.com/node/rewards-penalties#rewards.
