### ISSUE TITLE
bug: Checkpoint sync url error causing fail to start beacon node

### ISSUE THREAD

**Issue by zengzengzenghuy** [gnosischain/documentation#421]
## What

When running beacon node, the following checkpoint sync urls return error, causing the beacon node failed to start.

Checkpoint sync url
1. "https://checkpoint.gnosischain.com/":  CRIT Failed to start beacon node             reason: Checkpoint block at slot 8353568 is not aligned to epoch start. Please supply an aligned checkpoint with block.slot % 32 == 0
2. "https://checkpoint.gnosis.gateway.fm/": CRIT Failed to start beacon node             reason: Error fetching finalized block from remote: ServerMessage(ErrorMessage { code: 500, message: "not found", stacktraces: [] })
3. "https://checkpoint-sync-gnosis.dappnode.io/": no error 

Client: 
[Lighthouse v4.0.1](https://github.com/sigp/lighthouse/releases/tag/v4.0.1)

## Refs
- #343

**Comment by filoozom** [comment]
The Gateway and DAppNode endpoints work for me, the Gnosis doesn't. I've reported this to DevOps, we're looking into it.

**Comment by zengzengzenghuy** [comment]
yes I agree. Closing the issue here and moving discussion to https://github.com/gnosischain/issues/issues/16. Thanks @filoozom
