### ISSUE TITLE
bug: Lighthouse/Nethermind error when running lighthouse to sync beacon chain

### ISSUE THREAD

**Issue by mtr980** [gnosischain/documentation#429]
## What

Hi, following the instructions to validate on Macbook Pro, GNO deposits are done and currently showing Active-offline 
https://beacon.gnosischain.com/dashboard?validators=127015,127016,127017,127018,127019,127020,127021,127022,127023,127024

When I try to execute the lighthouse
./lighthouse \
--network gnosis beacon_node \
--datadir=data \
--http \
--execution-endpoint http://localhost:8551 \
--execution-jwt ../jwtsecret/jwt.hex \
--checkpoint-sync-url "https://checkpoint.gnosischain.com"

**Its been running for days now.getting the following errors**

Apr 18 12:38:27.501 INFO Syncing                                 est_time: --, distance: 94945 slots (5 days 11 hrs), peers: 16, service: slot_notifier
Apr 18 12:38:27.501 WARN Syncing deposit contract block cache    est_blocks_remaining: initializing deposits, service: slot_notifier
Apr 18 12:38:29.872 ERRO Error during execution engine upcheck   error: Reqwest(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("localhost")), port: Some(8551), path: "/", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 61, kind: ConnectionRefused, message: "Connection refused" })) }), service: exec
Apr 18 12:38:32.503 INFO Syncing                                 est_time: --, distance: 94946 slots (5 days 11 hrs), peers: 15, service: slot_notifier
Apr 18 12:38:32.503 WARN Syncing deposit contract block cache    est_blocks_remaining: initializing deposits, service: slot_notifier
Apr 18 12:38:34.876 ERRO Error during execution engine upcheck   error: Reqwest(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("localhost")), port: Some(8551), path: "/", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 61, kind: ConnectionRefused, message: "Connection refused" })) }), service: exec
Apr 18 12:38:37.501 INFO Syncing                                 est_time: --, distance: 94947 slots (5 days 11 hrs), peers: 13, service: slot_notifier

## Screenshot from MacOS terminal
![Screen Shot 2023-04-18 at 4 38 50 PM](https://user-images.githubusercontent.com/30289043/232781618-ee775859-83b4-45b8-a367-aeff3846e020.png)

**Comment by zengzengzenghuy** [comment]
Hi @mtr980 , the error is coming from "Connection refused" from Lighthouse to Nethermind. 

Can you check that if you add     `--JsonRpc.Enabled true ` and ` --JsonRpc.EnginePort=8551 ` options when running Nethermind client?

It would help if you can provide logs from Nethermind client too.
Thanks.

**Comment by mtr980** [comment]
> Hi @mtr980 , the error is coming from "Connection refused" from Lighthouse to Nethermind.
> 
> Can you check that if you add `--JsonRpc.Enabled true ` and `--JsonRpc.EnginePort=8551` options when running Nethermind client?
> 
> It would help if you can provide logs from Nethermind client too. Thanks.

Hi @zengzengzenghuy Yes.
./Nethermind.Runner \
    --config gnosis \
    --JsonRpc.Enabled true \
    --HealthChecks.Enabled true \
    --HealthChecks.UIEnabled true \
    --JsonRpc.EnginePort=8551 \
    --JsonRpc.JwtSecretFile=../jwtsecret/jwt.hex

**Comment by mtr980** [comment]
@zengzengzenghuy followed exactly as per https://docs.gnosischain.com/node/guide/

**Comment by zengzengzenghuy** [comment]
Your Nethermind client fails to load `secp256k1` dependencies. Did you install it correctly?
Please check if you have:
1. Install the correct version for your machine: https://downloads.nethermind.io/
2. Install the required dependencies: https://docs.nethermind.io/nethermind/ethereum-client/running-nethermind/running-the-client
