### ISSUE TITLE
content: Add Proof of Stake Consensus content under Protocol Specs

### ISSUE THREAD

**Issue by zengzengzenghuy** [gnosischain/documentation#433]
# What

At the About tab, under Protocol Specs -> Consensus, there are only AuRa and POSDAO, we need to add introduction about current consensus mechanism: Proof of Stake. 

![Screenshot from 2023-04-27 23-27-33](https://user-images.githubusercontent.com/85567868/234911891-c2a89bd0-416c-47ac-84c0-2f72af0d9108.png)

# How 

The content should includes:
1. What is Proof of Stake
2. Gasper
3. Weak subjectivity

# References
1. [Ethereum PoS](https://ethereum.org/en/developers/docs/consensus-mechanisms/pos/)

**Comment by AnmolSirola** [comment]
@zengzengzenghuy Can I work on this issue ?

**Comment by zengzengzenghuy** [comment]
Yeah @AnmolSirola, thank you :clap:

**Comment by AnmolSirola** [comment]
@zengzengzenghuy I have made a pr for this issue. Let me know if the content needs any changes.

**Comment by zengzengzenghuy** [comment]
Looks good! Can you add an entry to [sidebar.js](https://github.com/gnosischain/documentation/blob/main/sidebars.js#L99) as well?  #467

**Comment by AnmolSirola** [comment]
@zengzengzenghuy I can add but I don't know how to add 👎

**Comment by AnmolSirola** [comment]
@zengzengzenghuy I have added an entry for proof of stake.md to sidebar.js.
