### ISSUE TITLE
content: Infrastructure docs

### ISSUE THREAD

**Issue by ryanameier** [gnosischain/documentation#479]
**Tutorial title** Infrastructure

**Tutorial description**https://add3.io Add3 allows users to create smart contracts on-top of Gnosis (like token minting) within minutes instead of years.

**Tag your tutorial**Development

[**Publication**](https://docs.gnosischain.com/ecosystems/infrastructure)

**Skill level**

**For tutorials to be hosted on Gnosis: Tutorial Content**

[](https://docs.gnosischain.com/ecosystems/infrastructure)

**For tutorials hosted elsewhere: URL to tutorial**

**Comment by zengzengzenghuy** [comment]
Yes @AnmolSirola

**Comment by AnmolSirola** [comment]
@zengzengzenghuy
I am a bit confused about how and what to do in order to fix this issue. Can you please explain this issue to me?

**Comment by ryanameier** [comment]
@AnmolSirola 
https://docs.gnosischain.com/ecosystems/infrastructure
If you go to this link, we'd like to get added under "development" similar to the other companies you see there.
We can put: 

"[Add3](https://add3.io/) allows users to create smart contracts on-top of Gnosis (like token minting) in under 60 seconds instead of years."

**Comment by AnmolSirola** [comment]
@ryanameier I see, thanks for explaining :)
