### ISSUE TITLE
Content: Ecosystem Section that details DApps deployed on GC

### ISSUE THREAD

**Issue by alebanzas** [gnosischain/documentation#49]
<<edited by @dan-gnosis>>

## Description
- "Ecosystem" Section that has a page for each "category" of project
- We should do a round of "housekeeping" to get rid of deadpool-ed dApps that are no longer active
- Differentiate between "Featured" projects, vs. "Mentions"

## User Stories
- User should be able to see a list of all dApps in the Gnosis Chain ecosystem
- Each "category" should have a SEO-able page that lists the projects in that category with a short description
- Projects should be able to do a PR to the repo to add their project to the dApp page

![Image](https://user-images.githubusercontent.com/98335261/183807777-64966d35-9c04-4292-97f1-7be48a2618a7.png)

## Advanced User Stories
- There should be an optional way for projects to add a page for a project
- This page may not necessarily show up in the sidebar (just an internal link)
- The page URL will follow the following structure, e.g. 
`https://documentation.gnosischain.com/ecosystem/defi/uniswap`

![Image](https://user-images.githubusercontent.com/98335261/183807967-e6e61707-7756-4e80-b653-b7aec2941a8b.png)

## Resources
- [https://gnosischain.world/](https://gnosischain.world/)
- [https://developers.gnosischain.com/#project-highlights](https://developers.gnosischain.com/#project-highlights)

**Comment by dan-gnosis** [comment]
Some guidance on how to go through this:

![Image](https://user-images.githubusercontent.com/98335261/184003314-e53ca2a3-7b63-4d31-8db8-51aaaf51fd46.png)

**Comment by dan-gnosis** [comment]
@nitric - I've moved this task to the 29th Aug release, so please pick up on the core "Developers Section" tasks first
