### ISSUE TITLE
feat: ...

### ISSUE THREAD

**Issue by mtr980** [gnosischain/documentation#584]
## What

GUI to change OLD BLS (0x00  => 0x) and set new withdrawal credential

## Why
- Wagyu keygen only works for ethereum mainnet.
- Over a year, I tried everything but was not able to change withdrawal credentials.

## Refs

Raised with beacon chain https://github.com/gobitfly/eth2-beaconchain-explorer/issues/2761 but no luck.

**Comment by zengzengzenghuy** [comment]
Hey @mtr980 , if you're using Dappnode, the GUI is being developed by the team. Meanwhile, you can follow [this tutorial](https://docs.gnosischain.com/node/management/withdrawals#how-to-change-the-withdrawal-credential)  to change your withdrawal credential by using ethdo. For more details, please check: https://docs.gnosischain.com/faq/node/changingwc
