### ISSUE TITLE
Get Production Deployment for Gnosis Chain

### ISSUE THREAD

**Issue by dan-gnosis** [gnosischain/documentation#60]
- [x] [Redirects from old site](https://docs.google.com/spreadsheets/d/1ki1NJ3LscDpZHc1VI-zrM5p5tgNPo4MN4p-4wn7jYxg/edit)
- [x] DevOps support
- [x] Hide non-ready pages

**Comment by alebanzas** [comment]
URL selected: [docs.gnosischain.com](https://docs.gnosischain.com]
