### ISSUE TITLE
Improvements to "Deploying a Smart Contract'

### ISSUE THREAD

**Issue by dan-gnosis** [gnosischain/documentation#62]
Some areas for improvement

# Using Truffle

0. Title of the page should be "Using Truffle with Gnosis Chain" to enhance SEO-ability
- [x] Sidebar should still be "Using Truffle" while main page title is longer (enhance crawlability)
- [x] Please add SEO Metadata to the page -> https://docusaurus.io/docs/next/seo#single-page-metadata

1. Remove extraneous information from truffle code snapshot
- [x] Unnecessary config information in the snippet below. Junior devs might assume that things such as `truffle-hdwallet-provider`  are critical to the functioning, when they are not
- [x] The code snippet should show the path to the `truffle.js` file (see how it's done in the hardhat page)

![Image](https://user-images.githubusercontent.com/98335261/184016381-48cac7ad-8c87-44af-ab32-866b1e4b14a0.png)

2. Compiling a smart contract
- [x] Provide a default command, before one with option flags
- [x] Good to link to Truffle docs for the compile command -> https://trufflesuite.com/docs/truffle/reference/truffle-commands/#compile

```
# Compile for Gnosis
truffle compile --network gnosis

# Compile with options
truffle compile [--list <filter>] [--all] [--network gnosis] [--quiet]
```

![Image](https://user-images.githubusercontent.com/98335261/184016980-2750109c-dee6-45a9-a8ed-8336afb6f026.png)

3. Deploy your contract

4. Verify contract
- [x] Truffle Plugin Verify link is broken - read up on the Contract Verification Page and figure out what is the best documentation to write
- [x] Contract Verification Page link has a typo

# Using Hardhat

0. Title
- [x] Amend title (similar to Truffle)
- [x] Add SEO Metadata

1. Config Metadata for Gnosis
- [x] Remove irrelevant sections from the code snippet (also remove deprecated URL)

Is GetMnemonic() crucial for Gnosis development?

For "Change the TNetworkInfo variable to gnosis", the path_to_file needs to be the same as the previous 2 code snippets.
- [x] Why do we have a `hardhat.config.ts` file path
- [x] Should it be `hardhat.config.js` instead? (be agnostic to their file structure)

# Remix and Metamask

- [x] Amend title
- [x] Add SEO Metadata

1. Screenshots should be of a smaller resolution (currently very difficult to see). I would recommend reducing this to something that can be easily seen in the screenshot. 
2. Again, typo on "Contract Verfication Page"

For screenshots, the default is to use red arrows for visibility - see https://ethereum-blockchain-developer.com/110-upgrade-smart-contracts/08-eip-1822-uups/ for an example of a good tutorial

# Using Foundry

- [x] Needs to be done

**Comment by nitric** [comment]
@dan-gnosis can I add this [image zoom library](https://github.com/flexanalytics/plugin-image-zoom) for my image guides?

**Comment by dan-gnosis** [comment]
> @dan-gnosis can I add this [image zoom library](https://github.com/flexanalytics/plugin-image-zoom) for my image guides?
> 
> 
> 
> It's listed under the official [docusaurus resource page](https://docusaurus.io/community/resources#features:~:text=plugin%2Dimage%2Dzoom%20%2D%20An%20Image%20Zoom%20plugin%20for%20Docusaurus%202) 
> 
> 
> 
> My images are actually bigger than those shown in the example tutorial you showed, I think this would alleviate the issue

Good idea!
