### ISSUE TITLE
Bridge: Subwallet + Metamask + Chromium

### ISSUE THREAD

**Issue by Neozaru** [gnosischain/documentation#666]
https://bridge.gnosischain.com/

Subwallet takes over Metamask when trying to connect with Metamask using Firefox on Ubuntu 22

Sorry for being so short and not on the right repo, but I am short on time so alternative would be no report

**Comment by ilge-ustun** [comment]
Hi @Neozaru, thanks for heads up, we've fixed the issue of Subwallet extension
